name: CI

  # Temporarily disable workflow by removing triggers
#on: { }
# Original triggers (commented out for easy restoration):
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint and format
        run: npx biome check --no-errors-on-unmatched .

      - name: Generate types
        run: npx wrangler types

      - name: Run tests with coverage
        env:
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: false

      - name: Dry run deployment
        run: npm run deploy:dry